# Generated by Django 5.0.6 on 2024-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(blank=True, choices=[('W', 'Winter'), ('S', 'Sumer')], max_length=3, null=True),
        ),
    ]
